baseURL = "https://lostfutures.dev/"
theme='hugo-bearblog'
title = "Lost Futures"
pygmentsUseClasses = true
rssLimit = 10

author = "Chris Pauley"
copyright = ""
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  email = "chrispauley@protonmail.com"
  description = "Lost Futures is a blog by Chris Pauley"
  title = "Lost Futures"

[permalinks]
  blog = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true

[mediaTypes]

[outputFormats]
[outputs]
section = ["HTML", "RSS"]
