# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink: /:categories/:year/:month/:day/:title

# Setup
title:            v3x
tagline:          'dev blog'
description:      'Blog by <a href="https://github.com/chris-pauley" target="_blank">@chris-pauley</a>.'
url:              http://v3x.pw/blog
excerpt_separator: "<!--readmore-->"
#baseurl:          /blog

author:
  name:           'Chris Pauley'
  url:            https://twitter.com/chrispauley
  twitter:        'ChrisPauley'
  email:          'chrispauley@protonmail.com'

defaults:
    - scope:
        path: ""
        type: "posts"
      values:
          layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"


paginate:         5

plugins: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-feed]
# Custom vars
version:          2.1.0

github:
  repo:           "https://github.com/chris-pauley/blog"

links:
    github: "https://www.github.com/chris-pauley"
    twitter: "https://twitter.com/chrispauley"
    rss: "/atom.xml"
