# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            v3x
tagline:          'dev blog'
description:      'Authored by <a href="https://twitter.com/mdo" target="_blank">@chrispauley</a>.'
url:              http://v3x.pw/blog
baseurl:          /

author:
  name:           'Chris Pauley'
  url:            https://twitter.com/chrispauley

paginate:         5

gems: [jekyll-paginate, jekyll-gist]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chris-pauley/blog
