# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink: /:categories/:year/:month/:day/:title

# Setup
title:            v3x
tagline:          'dev blog'
description:      'Authored by <a href="https://github.com/chris-pauley" target="_blank">@chris-pauley</a>.'
url:              http://v3x.pw/blog
baseurl:          /blog

author:
  name:           'Chris Pauley'
  url:            https://twitter.com/chrispauley

paginate:         5

gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chris-pauley/blog
